services:
  uptime-kuma:
    container_name: "uptime-kuma"
    image: "louislam/uptime-kuma:2"
    ports:
      - "3001:3001/tcp"
    restart: "unless-stopped"
    volumes:
      - "/srv/uptime-kuma/data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
